//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudusingEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalIVRFlow
    {
        public int ID { get; set; }
        public string FlowName { get; set; }
        public string FlowDisplayName { get; set; }
        public Nullable<int> CampaignID { get; set; }
    }
}
