//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessControlList
    {
        public int ID { get; set; }
        public int AccessControlID { get; set; }
        public string AccessName { get; set; }
        public string FriendlyAccessName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AccessPanel AccessPanel { get; set; }
    }
}
