//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activitylog
    {
        public int ActivityLogID { get; set; }
        public string UserID { get; set; }
        public string Activity { get; set; }
        public string MachineName { get; set; }
        public string MachineIP { get; set; }
        public string PageName { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string Tag { get; set; }
    }
}
