//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentCallTimeStatu
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.TimeSpan IdleTime { get; set; }
        public System.TimeSpan BreakTime { get; set; }
        public System.TimeSpan TotalLoginTime { get; set; }
        public System.TimeSpan TotalTalkTime { get; set; }
        public Nullable<int> SendEmailCount { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<bool> IsSendEmail { get; set; }
        public Nullable<System.TimeSpan> ManualDialMode { get; set; }
        public Nullable<System.TimeSpan> ExtensionRinging { get; set; }
        public Nullable<System.TimeSpan> OutgoingCallDuration { get; set; }
        public Nullable<System.TimeSpan> IncommingCallDuration { get; set; }
        public Nullable<bool> IsEmailSendIdle { get; set; }
        public Nullable<bool> IsEmailSendBreak { get; set; }
        public Nullable<bool> IsEmailSendTLogin { get; set; }
        public Nullable<bool> IsEmailSendTTalk { get; set; }
        public Nullable<bool> IsEmailSendMDail { get; set; }
        public Nullable<bool> IsEmailSendExtRing { get; set; }
        public Nullable<bool> IsEmailSendOutCallDur { get; set; }
        public Nullable<bool> IsEmailSendInCallDur { get; set; }
    
        public virtual User User { get; set; }
    }
}
