//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppRolePermissionMapper
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int PermissionId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> SubRoleId { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual User User { get; set; }
        public virtual SubRole SubRole { get; set; }
    }
}
