//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchDetail()
        {
            this.UserBranchDetails = new HashSet<UserBranchDetail>();
        }
    
        public int BranchID { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string BranchPin { get; set; }
        public Nullable<int> CityId { get; set; }
        public bool Status { get; set; }
        public string BranchHeadName { get; set; }
        public string BranchFax { get; set; }
        public string BranchPhone1 { get; set; }
        public string BranchPhone2 { get; set; }
        public string BranchHeadTel { get; set; }
        public string BranchHeadMob { get; set; }
        public string BranchHeadEmail { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> CloudClientId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBranchDetail> UserBranchDetails { get; set; }
    }
}
