//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchGatewayMapping
    {
        public int ID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string BranchName { get; set; }
        public string Gateway { get; set; }
        public string GatewayIP { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
    }
}
