//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallListAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallListAttempt()
        {
            this.CallSuccesses = new HashSet<CallSuccess>();
        }
    
        public long ID { get; set; }
        public long CallListDetailsID { get; set; }
        public string Telephone { get; set; }
        public System.DateTime AttemptDate { get; set; }
        public int SystemDisposition { get; set; }
        public string ProcessInfo { get; set; }
        public Nullable<int> UserDisposition { get; set; }
        public string EndReason { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> PopupReceived { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<long> UserIdleTime { get; set; }
        public Nullable<System.DateTime> AttemptResultDate { get; set; }
        public Nullable<int> CallType { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallSuccess> CallSuccesses { get; set; }
    }
}
