//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallListDetailsAdditional
    {
        public long ID { get; set; }
        public long CallListDetailsID { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> Priority { get; set; }
        public string TelephoneType { get; set; }
        public bool Callable { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual CallListDetail CallListDetail { get; set; }
        public virtual CallListDetail CallListDetail1 { get; set; }
        public virtual CallListDetail CallListDetail2 { get; set; }
    }
}
