//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallSuccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallSuccess()
        {
            this.CallTransferSuccesses = new HashSet<CallTransferSuccess>();
        }
    
        public long ID { get; set; }
        public long CallListAttemptID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> ProcessEndDate { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public string ProcessInfo { get; set; }
        public Nullable<int> UserDisposition { get; set; }
        public string EndReason { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual CallListAttempt CallListAttempt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallTransferSuccess> CallTransferSuccesses { get; set; }
    }
}
