//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallListDetailsMobile
    {
        public long ID { get; set; }
        public Nullable<int> CallListID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> ScheduledTime { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string PolicyNo { get; set; }
        public string CustomerName { get; set; }
        public string Product { get; set; }
        public Nullable<int> TennatId { get; set; }
    }
}
