//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallList
    {
        public int ID { get; set; }
        public int CampaignID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<System.DateTime> DOM { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> BucketSize { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Prefix { get; set; }
        public Nullable<bool> IsPrefixActive { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
