//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Active { get; set; }
        public int Port { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<System.DateTime> DOM { get; set; }
        public short CallListType { get; set; }
        public Nullable<int> MaxAttempts { get; set; }
        public Nullable<int> HoldPromptID { get; set; }
        public int DispositionAlgorithm { get; set; }
        public Nullable<int> GreetingID { get; set; }
        public Nullable<int> CampaignMode { get; set; }
        public string CallFlow { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<int> CampaignDID { get; set; }
    }
}
