//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckDIDMapping
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string DIDNumber { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> Line { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
