//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetail
    {
        public int ID { get; set; }
        public string CallerId { get; set; }
        public string Name { get; set; }
        public string AlternateNumber { get; set; }
        public string Address { get; set; }
        public string AlternateAddress { get; set; }
        public string EmailID { get; set; }
        public string ServiceBranch { get; set; }
        public Nullable<System.DateTime> QuerySavedOn { get; set; }
        public string StoreName { get; set; }
        public string City { get; set; }
        public string Location { get; set; }
        public string ZomatoNumber { get; set; }
        public string OrderAmount { get; set; }
        public string IncommingCallId { get; set; }
        public string UserDisposition { get; set; }
    }
}
