//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication_Email_SMTPServer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Communication_Email_SMTPServer()
        {
            this.Communication_Email_Emails = new HashSet<Communication_Email_Emails>();
            this.Communication_Email_EmailsAttempts = new HashSet<Communication_Email_EmailsAttempts>();
        }
    
        public int ID { get; set; }
        public string Server { get; set; }
        public int Port { get; set; }
        public string Username { get; set; }
        public string Passphrase { get; set; }
        public Nullable<bool> RequireAuthentication { get; set; }
        public Nullable<bool> UseSSL { get; set; }
        public string FromAddress { get; set; }
        public string FromDisplayName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Communication_Email_Emails> Communication_Email_Emails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Communication_Email_EmailsAttempts> Communication_Email_EmailsAttempts { get; set; }
    }
}
