//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication_Email_EmailsAttachments
    {
        public int ID { get; set; }
        public int EmailsID { get; set; }
        public string Name { get; set; }
        public string FilePath { get; set; }
    
        public virtual Communication_Email_Emails Communication_Email_Emails { get; set; }
    }
}
