//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication_Email_Emails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Communication_Email_Emails()
        {
            this.Communication_Email_EmailsAttachments = new HashSet<Communication_Email_EmailsAttachments>();
            this.Communication_Email_EmailsAttempts = new HashSet<Communication_Email_EmailsAttempts>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PrefferredSMTPServerID { get; set; }
        public string EmailTo { get; set; }
        public string EmailCc { get; set; }
        public string EmailBcc { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsBodyHtml { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<System.DateTime> LastProcessedOn { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual Communication_Email_SMTPServer Communication_Email_SMTPServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Communication_Email_EmailsAttachments> Communication_Email_EmailsAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Communication_Email_EmailsAttempts> Communication_Email_EmailsAttempts { get; set; }
    }
}
