//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomField()
        {
            this.CampaignCustomFields = new HashSet<CampaignCustomField>();
        }
    
        public int ID { get; set; }
        public string SystemName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> Editable { get; set; }
        public Nullable<int> DisplayType { get; set; }
        public string DisplayItems { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignCustomField> CampaignCustomFields { get; set; }
    }
}
