//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailStatementRequestData
    {
        public int ID { get; set; }
        public string CallerID { get; set; }
        public string IncomingCallID { get; set; }
        public string FolioNo { get; set; }
        public string ARNNo { get; set; }
        public string EmailID { get; set; }
        public string Period_Type { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string PDF_Password { get; set; }
        public string PANNo { get; set; }
        public string SubRequestType { get; set; }
        public string RequestType { get; set; }
        public Nullable<System.DateTime> RequestDateTime { get; set; }
        public string CAMSReferenceNo { get; set; }
        public string CAMSResult { get; set; }
    }
}
