//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ID { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string ErrorDescription { get; set; }
        public string ExceptionDescription { get; set; }
        public string ErrorLocation { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ClientCode { get; set; }
        public string PageTitle { get; set; }
    }
}
