//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtensionMapping
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string Gateway { get; set; }
        public string Extension { get; set; }
        public Nullable<int> Campaign { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<System.DateTime> DOM { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
    }
}
