//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingCall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncomingCall()
        {
            this.IncomingDataReceiveds = new HashSet<IncomingDataReceived>();
        }
    
        public long ID { get; set; }
        public string CallerID { get; set; }
        public Nullable<System.DateTime> CallStart { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Remarks { get; set; }
        public int CallDispositionID { get; set; }
        public Nullable<System.DateTime> CallEnd { get; set; }
        public Nullable<System.DateTime> CallWrapUpTime { get; set; }
        public Nullable<long> HoldTime { get; set; }
        public Nullable<System.DateTime> UnHoldTime { get; set; }
        public Nullable<System.DateTime> TransferStart { get; set; }
        public Nullable<System.DateTime> TransferEnd { get; set; }
        public Nullable<short> GroupID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public string CalleeID { get; set; }
        public Nullable<int> CalledUser { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ChannelId { get; set; }
        public string BaseCallerId { get; set; }
        public string BranchCode { get; set; }
        public Nullable<bool> IsSynchronised { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomingDataReceived> IncomingDataReceiveds { get; set; }
    }
}
