//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingEmail_Settings
    {
        public int Id { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string out_emailid { get; set; }
        public string IncomingAliasEmail { get; set; }
        public byte[] out_password { get; set; }
        public byte[] Password { get; set; }
        public string IncomingMailserver { get; set; }
        public string IncomingPort { get; set; }
        public string OutgoingMailServer { get; set; }
        public string OutgoingPort { get; set; }
        public Nullable<bool> IsSSL { get; set; }
        public Nullable<int> UserRole { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
