//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsertOptionSelection
    {
        public long ID { get; set; }
        public long IncomingCallID { get; set; }
        public string CallerID { get; set; }
        public string Language { get; set; }
        public string OptionSelected { get; set; }
        public string FolioNumber { get; set; }
        public Nullable<System.DateTime> CallDateTime { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
