//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalTransfer
    {
        public long ID { get; set; }
        public Nullable<long> CallReceivedID { get; set; }
        public Nullable<long> IncomingTransferSuccessID { get; set; }
        public Nullable<int> TransferInitiatorUserID { get; set; }
        public Nullable<int> TransferredToUserID { get; set; }
        public Nullable<System.DateTime> TransferredDate { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
