//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVRFlowTrace
    {
        public long ID { get; set; }
        public long IncomingCallsID { get; set; }
        public Nullable<System.DateTime> ResponseDateTime { get; set; }
        public Nullable<int> ActionType { get; set; }
        public string NodeName { get; set; }
        public string DtmfReceived { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
