//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualDialAttempt
    {
        public string ID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CallListDispositionsID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> AttemptDateTime { get; set; }
        public Nullable<System.DateTime> CallStartTime { get; set; }
        public Nullable<System.DateTime> CallEndTime { get; set; }
        public string Telephone { get; set; }
        public Nullable<long> HoldTime { get; set; }
        public Nullable<int> SystemDisposition { get; set; }
        public Nullable<short> CallBack { get; set; }
        public string LinkID { get; set; }
        public Nullable<System.DateTime> ScheduledDateTime { get; set; }
        public string ReferenceID { get; set; }
        public string BranchCode { get; set; }
        public Nullable<bool> IsSynchronised { get; set; }
        public string ClientCode { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
