//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallbalanceClopsEntities : DbContext
    {
        public CallbalanceClopsEntities()
            : base("name=CallbalanceClopsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accesscontrollist> accesscontrollists { get; set; }
        public virtual DbSet<accesspanel> accesspanels { get; set; }
        public virtual DbSet<activitylog> activitylogs { get; set; }
        public virtual DbSet<addressbook> addressbooks { get; set; }
        public virtual DbSet<adminmenu> adminmenus { get; set; }
        public virtual DbSet<agentcalltimestatuslog> agentcalltimestatuslogs { get; set; }
        public virtual DbSet<alertdescription> alertdescriptions { get; set; }
        public virtual DbSet<blockcallerlist> blockcallerlists { get; set; }
        public virtual DbSet<boardmodel> boardmodels { get; set; }
        public virtual DbSet<branchdetail> branchdetails { get; set; }
        public virtual DbSet<branchgatewaymapping> branchgatewaymappings { get; set; }
        public virtual DbSet<branchmaster> branchmasters { get; set; }
        public virtual DbSet<@break> breaks { get; set; }
        public virtual DbSet<call_category> call_category { get; set; }
        public virtual DbSet<callbacksmissed> callbacksmisseds { get; set; }
        public virtual DbSet<callconnectiondetail> callconnectiondetails { get; set; }
        public virtual DbSet<calldestinationmaster> calldestinationmasters { get; set; }
        public virtual DbSet<calldisposition> calldispositions { get; set; }
        public virtual DbSet<calllist> calllists { get; set; }
        public virtual DbSet<calllistattempt> calllistattempts { get; set; }
        public virtual DbSet<calllistdetail> calllistdetails { get; set; }
        public virtual DbSet<calllistdetailsadditional> calllistdetailsadditionals { get; set; }
        public virtual DbSet<calllistdetailsmobile> calllistdetailsmobiles { get; set; }
        public virtual DbSet<callsuccess> callsuccesses { get; set; }
        public virtual DbSet<calltransfersuccess> calltransfersuccesses { get; set; }
        public virtual DbSet<campaign> campaigns { get; set; }
        public virtual DbSet<campaignchannel> campaignchannels { get; set; }
        public virtual DbSet<campaigncustomfield> campaigncustomfields { get; set; }
        public virtual DbSet<campaigndisposition> campaigndispositions { get; set; }
        public virtual DbSet<campaignsetting> campaignsettings { get; set; }
        public virtual DbSet<campaignusergroup> campaignusergroups { get; set; }
        public virtual DbSet<campaignuser> campaignusers { get; set; }
        public virtual DbSet<campaignverifier> campaignverifiers { get; set; }
        public virtual DbSet<channel> channels { get; set; }
        public virtual DbSet<checkdidmapping> checkdidmappings { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<clientdetail> clientdetails { get; set; }
        public virtual DbSet<communication_email_emails> communication_email_emails { get; set; }
        public virtual DbSet<communication_email_emailsattachments> communication_email_emailsattachments { get; set; }
        public virtual DbSet<communication_email_emailsattempts> communication_email_emailsattempts { get; set; }
        public virtual DbSet<communication_email_settings> communication_email_settings { get; set; }
        public virtual DbSet<communication_email_smtpserver> communication_email_smtpserver { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customfield> customfields { get; set; }
        public virtual DbSet<dnclist> dnclists { get; set; }
        public virtual DbSet<emailstatementrequestdata> emailstatementrequestdatas { get; set; }
        public virtual DbSet<errorlog> errorlogs { get; set; }
        public virtual DbSet<extensionmapping> extensionmappings { get; set; }
        public virtual DbSet<extension> extensions { get; set; }
        public virtual DbSet<flag> flags { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<hmpdetail> hmpdetails { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<incomingcall> incomingcalls { get; set; }
        public virtual DbSet<incomingdatareceived> incomingdatareceiveds { get; set; }
        public virtual DbSet<incomingtransferfailed> incomingtransferfaileds { get; set; }
        public virtual DbSet<incomingtransferfailed_history> incomingtransferfailed_history { get; set; }
        public virtual DbSet<incomingtransfersuccess> incomingtransfersuccesses { get; set; }
        public virtual DbSet<insertoptionselection> insertoptionselections { get; set; }
        public virtual DbSet<internaltransfer> internaltransfers { get; set; }
        public virtual DbSet<ivrflowtrace> ivrflowtraces { get; set; }
        public virtual DbSet<leadmanagement> leadmanagements { get; set; }
        public virtual DbSet<leadtype> leadtypes { get; set; }
        public virtual DbSet<manualdialattempt> manualdialattempts { get; set; }
        public virtual DbSet<mobileactivity> mobileactivities { get; set; }
        public virtual DbSet<nonbusinesshourcall> nonbusinesshourcalls { get; set; }
        public virtual DbSet<officeservicetype> officeservicetypes { get; set; }
        public virtual DbSet<officetime> officetimes { get; set; }
        public virtual DbSet<otpgeneration> otpgenerations { get; set; }
        public virtual DbSet<passwordpolicy> passwordpolicies { get; set; }
        public virtual DbSet<pbxextension> pbxextensions { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<permission1> permissions1 { get; set; }
        public virtual DbSet<plan> plans { get; set; }
        public virtual DbSet<plansetting> plansettings { get; set; }
        public virtual DbSet<priinfo> priinfoes { get; set; }
        public virtual DbSet<rmclientmapping> rmclientmappings { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<rolepermission> rolepermissions { get; set; }
        public virtual DbSet<role1> roles1 { get; set; }
        public virtual DbSet<rule> rules { get; set; }
        public virtual DbSet<ruleaction> ruleactions { get; set; }
        public virtual DbSet<rulealert> rulealerts { get; set; }
        public virtual DbSet<ruleprocess> ruleprocesses { get; set; }
        public virtual DbSet<securityquestion> securityquestions { get; set; }
        public virtual DbSet<service_category> service_category { get; set; }
        public virtual DbSet<service_type> service_type { get; set; }
        public virtual DbSet<setdigit> setdigits { get; set; }
        public virtual DbSet<setformat> setformats { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<sipusermapping> sipusermappings { get; set; }
        public virtual DbSet<sipusermaster> sipusermasters { get; set; }
        public virtual DbSet<speeddial> speeddials { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<state1> states1 { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<storemaster> storemasters { get; set; }
        public virtual DbSet<subrole> subroles { get; set; }
        public virtual DbSet<subrolepermissionmapper> subrolepermissionmappers { get; set; }
        public virtual DbSet<systemalert> systemalerts { get; set; }
        public virtual DbSet<systemdisposition> systemdispositions { get; set; }
        public virtual DbSet<systemuserpermission> systemuserpermissions { get; set; }
        public virtual DbSet<tenantaudit> tenantaudits { get; set; }
        public virtual DbSet<tenant> tenants { get; set; }
        public virtual DbSet<user_cti_details> user_cti_details { get; set; }
        public virtual DbSet<useractivity> useractivities { get; set; }
        public virtual DbSet<userbranchaccess> userbranchaccesses { get; set; }
        public virtual DbSet<userbranchdetail> userbranchdetails { get; set; }
        public virtual DbSet<userbranchmapping> userbranchmappings { get; set; }
        public virtual DbSet<userbreak> userbreaks { get; set; }
        public virtual DbSet<usercampaignmapping> usercampaignmappings { get; set; }
        public virtual DbSet<userdefinedrole> userdefinedroles { get; set; }
        public virtual DbSet<userdefinedroledetail> userdefinedroledetails { get; set; }
        public virtual DbSet<usergroupdetail> usergroupdetails { get; set; }
        public virtual DbSet<usergroup> usergroups { get; set; }
        public virtual DbSet<userlog> userlogs { get; set; }
        public virtual DbSet<usermappingwithuserdefinedrole> usermappingwithuserdefinedroles { get; set; }
        public virtual DbSet<usermissedcalldetail> usermissedcalldetails { get; set; }
        public virtual DbSet<usermobilemapping> usermobilemappings { get; set; }
        public virtual DbSet<userpermission> userpermissions { get; set; }
        public virtual DbSet<userprofile> userprofiles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<usersecurity> usersecurities { get; set; }
        public virtual DbSet<usersinrole> usersinroles { get; set; }
        public virtual DbSet<userstatu> userstatus { get; set; }
        public virtual DbSet<verifier> verifiers { get; set; }
        public virtual DbSet<voicelogs_calldetails> voicelogs_calldetails { get; set; }
        public virtual DbSet<voicemail> voicemails { get; set; }
        public virtual DbSet<workstation> workstations { get; set; }
        public virtual DbSet<zone> zones { get; set; }
    }
}
