//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OceanEntities : DbContext
    {
        public OceanEntities()
            : base("name=OceanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AccessControlList> AccessControlLists { get; set; }
        public virtual DbSet<AccessPanel> AccessPanels { get; set; }
        public virtual DbSet<Activitylog> Activitylogs { get; set; }
        public virtual DbSet<AddressBook> AddressBooks { get; set; }
        public virtual DbSet<AgentCallTimeStatu> AgentCallTimeStatus { get; set; }
        public virtual DbSet<AgentCallTimeStatusLog> AgentCallTimeStatusLogs { get; set; }
        public virtual DbSet<AlertDescription> AlertDescriptions { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<AppRolePermissionMapper> AppRolePermissionMappers { get; set; }
        public virtual DbSet<BlockCallerList> BlockCallerLists { get; set; }
        public virtual DbSet<BranchDetail> BranchDetails { get; set; }
        public virtual DbSet<BranchGatewayMapping> BranchGatewayMappings { get; set; }
        public virtual DbSet<BranchMaster> BranchMasters { get; set; }
        public virtual DbSet<Break> Breaks { get; set; }
        public virtual DbSet<CallBacksMissed> CallBacksMisseds { get; set; }
        public virtual DbSet<CallDestinationMaster> CallDestinationMasters { get; set; }
        public virtual DbSet<CallDisposition> CallDispositions { get; set; }
        public virtual DbSet<CallList> CallLists { get; set; }
        public virtual DbSet<CallListAttempt> CallListAttempts { get; set; }
        public virtual DbSet<CallListDetail> CallListDetails { get; set; }
        public virtual DbSet<CallListDetailsAdditional> CallListDetailsAdditionals { get; set; }
        public virtual DbSet<CallListDetailsMobile> CallListDetailsMobiles { get; set; }
        public virtual DbSet<CallSuccess> CallSuccesses { get; set; }
        public virtual DbSet<CallTransferSuccess> CallTransferSuccesses { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<CampaignChannel> CampaignChannels { get; set; }
        public virtual DbSet<CampaignCustomField> CampaignCustomFields { get; set; }
        public virtual DbSet<CampaignDisposition> CampaignDispositions { get; set; }
        public virtual DbSet<CampaignSetting> CampaignSettings { get; set; }
        public virtual DbSet<CampaignUserGroup> CampaignUserGroups { get; set; }
        public virtual DbSet<CampaignUser> CampaignUsers { get; set; }
        public virtual DbSet<CampaignVerifier> CampaignVerifiers { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ClientDetail> ClientDetails { get; set; }
        public virtual DbSet<Communication_Email_Emails> Communication_Email_Emails { get; set; }
        public virtual DbSet<Communication_Email_EmailsAttachments> Communication_Email_EmailsAttachments { get; set; }
        public virtual DbSet<Communication_Email_EmailsAttempts> Communication_Email_EmailsAttempts { get; set; }
        public virtual DbSet<Communication_Email_Settings> Communication_Email_Settings { get; set; }
        public virtual DbSet<Communication_Email_SMTPServer> Communication_Email_SMTPServer { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomField> CustomFields { get; set; }
        public virtual DbSet<DNCList> DNCLists { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<ExtensionMapping> ExtensionMappings { get; set; }
        public virtual DbSet<Extension> Extensions { get; set; }
        public virtual DbSet<Flag> Flags { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<HMPDetail> HMPDetails { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<IncomingCall> IncomingCalls { get; set; }
        public virtual DbSet<IncomingDataReceived> IncomingDataReceiveds { get; set; }
        public virtual DbSet<IncomingEmail_Settings> IncomingEmail_Settings { get; set; }
        public virtual DbSet<IncomingTransferFailed_History> IncomingTransferFailed_History { get; set; }
        public virtual DbSet<InternalTransfer> InternalTransfers { get; set; }
        public virtual DbSet<IVRFlowTrace> IVRFlowTraces { get; set; }
        public virtual DbSet<LeadManagement> LeadManagements { get; set; }
        public virtual DbSet<LeadType> LeadTypes { get; set; }
        public virtual DbSet<ManualDialAttempt> ManualDialAttempts { get; set; }
        public virtual DbSet<NonBusinessHourCall> NonBusinessHourCalls { get; set; }
        public virtual DbSet<OfficeServiceType> OfficeServiceTypes { get; set; }
        public virtual DbSet<OfficeTime> OfficeTimes { get; set; }
        public virtual DbSet<OrganizationDetail> OrganizationDetails { get; set; }
        public virtual DbSet<PasswordPolicy> PasswordPolicies { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<PlanSetting> PlanSettings { get; set; }
        public virtual DbSet<PRIInfo> PRIInfoes { get; set; }
        public virtual DbSet<RMClientMapping> RMClientMappings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role1> Roles1 { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<RuleAction> RuleActions { get; set; }
        public virtual DbSet<RuleAlert> RuleAlerts { get; set; }
        public virtual DbSet<RuleProcess> RuleProcesses { get; set; }
        public virtual DbSet<SecurityQuestion> SecurityQuestions { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SIPUserMapping> SIPUserMappings { get; set; }
        public virtual DbSet<SIPUserMaster> SIPUserMasters { get; set; }
        public virtual DbSet<SpeedDial> SpeedDials { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<State1> States1 { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StoreMaster> StoreMasters { get; set; }
        public virtual DbSet<SubRole> SubRoles { get; set; }
        public virtual DbSet<SubRolePermissionMapper> SubRolePermissionMappers { get; set; }
        public virtual DbSet<SystemAlert> SystemAlerts { get; set; }
        public virtual DbSet<SystemDisposition> SystemDispositions { get; set; }
        public virtual DbSet<TenantAudit> TenantAudits { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_CTI_Details> User_CTI_Details { get; set; }
        public virtual DbSet<UserActivity> UserActivities { get; set; }
        public virtual DbSet<UserBranchAccess> UserBranchAccesses { get; set; }
        public virtual DbSet<UserBranchDetail> UserBranchDetails { get; set; }
        public virtual DbSet<UserBranchMapping> UserBranchMappings { get; set; }
        public virtual DbSet<UserBreak> UserBreaks { get; set; }
        public virtual DbSet<UserCampaignMapping> UserCampaignMappings { get; set; }
        public virtual DbSet<UserDefinedRole> UserDefinedRoles { get; set; }
        public virtual DbSet<UserGroupDetail> UserGroupDetails { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<UserMappingwithUserDefinedRole> UserMappingwithUserDefinedRoles { get; set; }
        public virtual DbSet<UserMissedCallDetail> UserMissedCallDetails { get; set; }
        public virtual DbSet<UserMobileMapping> UserMobileMappings { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<Users_Audit> Users_Audit { get; set; }
        public virtual DbSet<UserSecurity> UserSecurities { get; set; }
        public virtual DbSet<UsersInRole> UsersInRoles { get; set; }
        public virtual DbSet<UserStatu> UserStatus { get; set; }
        public virtual DbSet<Verifier> Verifiers { get; set; }
        public virtual DbSet<VoiceLogs_CallDetails> VoiceLogs_CallDetails { get; set; }
        public virtual DbSet<VoiceMail> VoiceMails { get; set; }
        public virtual DbSet<Workstation> Workstations { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
        public virtual DbSet<AdminMenu> AdminMenus { get; set; }
        public virtual DbSet<BoardModel> BoardModels { get; set; }
        public virtual DbSet<Call_Category> Call_Category { get; set; }
        public virtual DbSet<CallConnectionDetail> CallConnectionDetails { get; set; }
        public virtual DbSet<CheckDIDMapping> CheckDIDMappings { get; set; }
        public virtual DbSet<EmailStatementRequestData> EmailStatementRequestDatas { get; set; }
        public virtual DbSet<IncomingTransferFailed> IncomingTransferFaileds { get; set; }
        public virtual DbSet<IncomingTransferSuccess> IncomingTransferSuccesses { get; set; }
        public virtual DbSet<InsertOptionSelection> InsertOptionSelections { get; set; }
        public virtual DbSet<MobileActivity> MobileActivities { get; set; }
        public virtual DbSet<OTPGeneration> OTPGenerations { get; set; }
        public virtual DbSet<PbxExtension> PbxExtensions { get; set; }
        public virtual DbSet<Permission1> Permissions1 { get; set; }
        public virtual DbSet<Service_Category> Service_Category { get; set; }
        public virtual DbSet<Service_Type> Service_Type { get; set; }
        public virtual DbSet<SetDigit> SetDigits { get; set; }
        public virtual DbSet<SetFormat> SetFormats { get; set; }
        public virtual DbSet<SystemUserPermission> SystemUserPermissions { get; set; }
        public virtual DbSet<UserDefinedRoleDetail> UserDefinedRoleDetails { get; set; }
    }
}
