//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeTime
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Servicetype { get; set; }
        public string Days { get; set; }
        public Nullable<int> WeekDay { get; set; }
        public Nullable<bool> IsWorkingDay { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
