//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationDetail
    {
        public int OrgID { get; set; }
        public string OrgName { get; set; }
        public string OrgOwnerName { get; set; }
        public string OrgAdd1 { get; set; }
        public string OrgAdd2 { get; set; }
        public string OrgAdd3 { get; set; }
        public string OrgCity { get; set; }
        public string OrgPin { get; set; }
        public string OrgState { get; set; }
        public string OrgCountry { get; set; }
        public string OrgURL { get; set; }
        public string OrgPhone1 { get; set; }
        public string OrgPhone2 { get; set; }
        public string OrgEmail { get; set; }
        public string OrgFax { get; set; }
        public string LogoPath { get; set; }
        public byte[] LogoImage { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
