//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordPolicy
    {
        public int Id { get; set; }
        public int LoginAttempt { get; set; }
        public int MinPswrdLength { get; set; }
        public int MaxPswrdLength { get; set; }
        public int MinNumCount { get; set; }
        public int MinSymbolCount { get; set; }
        public int MinCapCharacterCount { get; set; }
        public int ExpInDays { get; set; }
        public int UnBLockTimeinHours { get; set; }
        public int Session_Timeout_min_ { get; set; }
        public int Re_use_Password_After_Attempts_ { get; set; }
        public string StandardPassword { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
