//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PbxExtension
    {
        public int ID { get; set; }
        public int ChannelID { get; set; }
        public string Number { get; set; }
        public System.DateTime DOM { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Campaign { get; set; }
        public Nullable<int> FlowNumber { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<bool> CreateVoicelink { get; set; }
    }
}
