//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMClientMapping
    {
        public int Id { get; set; }
        public string ClientID { get; set; }
        public string ContactNo { get; set; }
        public string Userid { get; set; }
        public string BranchCode { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DID { get; set; }
        public string Client_Name { get; set; }
        public string Contact_No2 { get; set; }
        public string Contact_No1 { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
