//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int id { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> PermissionID { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual Role1 Role { get; set; }
    }
}
