//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleAction
    {
        public int ID { get; set; }
        public Nullable<int> RuleID { get; set; }
        public Nullable<int> ActionType { get; set; }
        public string ActionValues { get; set; }
        public string ActionMessage { get; set; }
        public string UserId { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
