//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetDigit
    {
        public int ID { get; set; }
        public string Digit { get; set; }
        public string FilePath { get; set; }
        public string Mode { get; set; }
    }
}
