//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeedDial
    {
        public int ID { get; set; }
        public string Shortcut { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ContactName { get; set; }
        public Nullable<bool> IsSystemGenerated { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
