//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class State1
    {
        public int StateID { get; set; }
        public string StateName { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
