//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubRolePermissionMapper
    {
        public int ID { get; set; }
        public Nullable<int> SubRoleID { get; set; }
        public int PermissionId { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual SubRole SubRole { get; set; }
    }
}
