//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubRole()
        {
            this.AppRolePermissionMappers = new HashSet<AppRolePermissionMapper>();
            this.SubRolePermissionMappers = new HashSet<SubRolePermissionMapper>();
        }
    
        public int SubRoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppRolePermissionMapper> AppRolePermissionMappers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubRolePermissionMapper> SubRolePermissionMappers { get; set; }
    }
}
