//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemAlert
    {
        public int ID { get; set; }
        public int SystemAlertType { get; set; }
        public Nullable<System.DateTime> AlertDateTime { get; set; }
        public string Message { get; set; }
        public Nullable<int> ExtraInfo { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
