//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantAudit
    {
        public int ID { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<int> PlanID { get; set; }
        public Nullable<System.DateTime> planActivateDate { get; set; }
        public Nullable<System.DateTime> PlanExpirDate { get; set; }
        public string PulseUsed { get; set; }
        public Nullable<System.DateTime> LastUpdateDatetime { get; set; }
    }
}
