//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMissedCallDetail
    {
        public int ID { get; set; }
        public Nullable<long> CallReceivedID { get; set; }
        public string CallerID { get; set; }
        public string BranchCode { get; set; }
        public string ProductType { get; set; }
        public string ClientName { get; set; }
        public string ClientCode { get; set; }
        public Nullable<System.DateTime> CallDateTime { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> AssignDateTime { get; set; }
        public Nullable<bool> IsDialed { get; set; }
        public Nullable<System.DateTime> DialedDateTime { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
