//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Audit
    {
        public int UA_ID { get; set; }
        public int UserID { get; set; }
        public string UserFName { get; set; }
        public string UserMName { get; set; }
        public string UserLName { get; set; }
        public Nullable<int> UserRole { get; set; }
        public string UserEmail { get; set; }
        public string UserPhoneCode { get; set; }
        public string UserPhone { get; set; }
        public string UserMobile { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public bool IsActive { get; set; }
        public bool CanBeDeleted { get; set; }
        public Nullable<System.DateTime> UserCreatedOn { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public bool EmailValid { get; set; }
        public string VerifyImageText { get; set; }
        public bool IsBlock { get; set; }
        public Nullable<System.DateTime> BlockTime { get; set; }
        public byte[] UserPassword { get; set; }
        public string EmailSignature { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<int> Question_ID { get; set; }
        public byte[] Answer { get; set; }
        public Nullable<int> UpdatePassword { get; set; }
        public string UserDescription { get; set; }
        public Nullable<int> CurrentUserID { get; set; }
        public Nullable<System.DateTime> InsertedOn_Date { get; set; }
    }
}
