//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBreak
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public System.DateTime BreakStart { get; set; }
        public Nullable<System.DateTime> BreakStop { get; set; }
        public string Reason { get; set; }
        public string BranchCode { get; set; }
        public Nullable<bool> IsSynchronised { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual UserBreak UserBreaks1 { get; set; }
        public virtual UserBreak UserBreak1 { get; set; }
    }
}
