//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBranchDetail
    {
        public int ID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual BranchDetail BranchDetail { get; set; }
        public virtual State State { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
