//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBranchMapping
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int BranchId { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
