//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_CTI_Details
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CurrentCampaign { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Workstation { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> StatusDateTime { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string BranchCode { get; set; }
        public Nullable<bool> IsLoggedIn { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
