//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoiceMail
    {
        public int Id { get; set; }
        public string IncommingCallId { get; set; }
        public string CallerId { get; set; }
        public string SelectedOption { get; set; }
        public string WavFile { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<System.DateTime> RecordDtTime { get; set; }
        public Nullable<System.DateTime> PlayedDtTime { get; set; }
        public Nullable<int> DispositionId { get; set; }
        public Nullable<int> PlayedBy { get; set; }
        public Nullable<short> AssignedTo { get; set; }
        public Nullable<short> AssignedBy { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string TicketNo { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> IsPlayed { get; set; }
        public Nullable<bool> IsAbandond { get; set; }
        public string ManualDailId { get; set; }
        public Nullable<int> AuditId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
