//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workstation
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string IPAddress { get; set; }
        public string Extension { get; set; }
        public string BranchCode { get; set; }
        public string FXO { get; set; }
        public string FXS { get; set; }
        public string PhysicalExtension { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
