//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudusingEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int rid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Dateofbirth { get; set; }
        public string Gender { get; set; }
        public string Contact_no { get; set; }
        public string course { get; set; }
        public string OtherCourses { get; set; }
        public string Address { get; set; }
        public string city { get; set; }
    }
}
