//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudusingEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public int zoneId { get; set; }
        public string zoneName { get; set; }
        public Nullable<int> Is_Deleted { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
